# Generated by Django 5.1.7 on 2025-03-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
